######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 3 03:56:24 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += syssec.h
FORMS += syssec.ui
SOURCES += main.cpp syssec.cpp
